name: snap_pay_repository
description: Paquete de dart para manejar los repositorios de datos
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  snap_pay_api:
    path: ../snap_pay_api