name: snap_pay_local_storage_api
description: Paquete de dart para gestionar el almacenamiento local
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  snap_pay_api:
    path: ../snap_pay_api
  shared_preferences: ^2.5.3

dev_dependencies:
  json_serializable: ^6.9.4